name: Test

on:
  schedule:
    - cron: '0 4 * * 6'
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Run ${{ github.repository }}@${{ github.sha }}
        uses: ./

      - name: Show lxc info
        run: lxc info
